@host=http://localhost:8081
@version=v1
@description=Ledger-Endpoints-CashDeposit
@baseurl={{host}}/v1

###
# @name deposit
POST {{baseurl}}/ledger-deposit
Content-Type: application/json

{
  "amount": "20"
}